<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Language\**" />
    <Compile Remove="Resources\**" />
    <EmbeddedResource Remove="Language\**" />
    <EmbeddedResource Remove="Resources\**" />
    <None Remove="Language\**" />
    <None Remove="Resources\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="2.10.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.1.2" />
  </ItemGroup>
</Project>
