<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="Current">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <FileUpgradeFlags>
    </FileUpgradeFlags>
    <UpgradeBackupLocation>
    </UpgradeBackupLocation>
    <OldToolsVersion>2.0</OldToolsVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Data.Models\Data.Models.csproj" />
    <ProjectReference Include="..\Data\Data.csproj" />
    <ProjectReference Include="..\Providers\Providers.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="3.1.2" />
    <PackageReference Include="RestSharp" Version="106.10.1" />
    <PackageReference Include="StackExchange.Redis.Extensions.Core" Version="5.5.0" />
    <PackageReference Include="StackExchange.Redis.Extensions.Newtonsoft" Version="5.5.0" />
  </ItemGroup>
</Project>