<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Migrations\20190903053228_TypeField.cs" />
    <Compile Remove="Migrations\20190903053228_TypeField.Designer.cs" />
    <Compile Remove="Migrations\20191105113111_BrandTranslations.cs" />
    <Compile Remove="Migrations\20191105113111_BrandTranslations.Designer.cs" />
    <Compile Remove="Migrations\20191108131354_HotelTranslationUpdated.cs" />
    <Compile Remove="Migrations\20191108131354_HotelTranslationUpdated.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="3.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.1" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="3.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data.Models\Data.Models.csproj" />
  </ItemGroup>

</Project>
